isDevelopment: true
staticSystemPath: "./src/build/static"
staticRequestPath: "/static"
templateServe: "./src/template"
templateSuffix: ".html"
faviconPath: "./src/build/static/img/favicon.ico"
logFilePath: "./log/log.log"
pay:
  wechat:
    appid: ""
    mch_id: ""
    apiKey: ""
server:
  host: "0.0.0.0"
  port: 8080
  captcha:
    key: "CAPTCHA"
    font-path: "./resource/font/comic.ttf"
  rate-limiter:
    rate: "10-M"
    redis:
      addr: "127.0.0.1:6379"
      password: ""
      database: 10
      prefix: "soda-manager-rate-limiter:"
      max-retry: 3
  session:
    user:
      user-id-key: "userid"
    cookie: "sess"
    expires: 3600
    redis:
      addr: "127.0.0.1:6379"
      password: ""
      database: 10
      prefix: "soda-manager-session:"
      max-idle: 20
      max-active: 50
      max-age-seconds: 3600
      idle-timeout: 60
  db:
    dialect: "mysql"
    host: "127.0.0.1"
    port: 3306
    user: "root"
    password: ""
    database: "soda-manager"
    max-idle: 20
    max-open: 20
  mndb:
    dialect: "mysql"
    host: "120.24.248.223"
    port: 3306
    user: "boxadmin"
    password: "db@ba1306"
    database: "mnzn"
    max-idle: 20
    max-open: 20
  redis:
        addr: "127.0.0.1:6379"
        password: ""
        database: 10
        prefix: "soda-manager:"
        max-idle: 20
        max-active: 50
        idle-timeout: 60

