isDevelopment: true
staticSystemPath: "./src/build/static"
staticRequestPath: "/static"
templateServe: "./src/build/template"
templateSuffix: ".html"
faviconPath: "./src/build/static/img/favicon.ico"
logFilePath: "/data/logs/maizuo.log"
pay:
  wechat:
    appid: ""
    mch_id: ""
    apiKey: ""
server:
  host: "0.0.0.0"
  port: 9999
  captcha:
    key: "CAPTCHA"
    font-path: "./resource/font/comic.ttf"
  rate-limiter:
    rate: "10-M"
    redis:
      addr: "192.168.1.204:6379"
      password: "123456"
      database: 10
      prefix: "soda-manager-rate-limiter:"
      max-retry: 3
  session:
    user:
      id: "USERID"
      key: "USER"
    cookie: "sess"
    expires: 3600
    redis:
      addr: "192.168.1.204:6379"
      password: "123456"
      database: 10
      prefix: "soda-manager-session:"
      max-idle: 20
      max-active: 50
      max-age-seconds: 3600
      idle-timeout: 60
  db:
    dialect: "mysql"
    host: "192.168.1.204"
    port: 3306
    user: "web"
    password: "123456"
    database: "soda-manager"
    max-idle: 20
    max-open: 20
  mndb:
      dialect: "mysql"
      host: "192.168.1.204"
      port: 3306
      user: "web"
      password: "123456"
      database: "mnzn"
      max-idle: 20
      max-open: 20
  redis:
        addr: "192.168.1.204:6379"
        password: "123456"
        database: 10
        prefix: "soda-manager:"
        max-idle: 20
        max-active: 50
        idle-timeout: 60
