isDevelopment: true
staticSystemPath: "./src/build/static"
staticRequestPath: "/static"
templateServe: "./src/build/template"
templateSuffix: ".html"
faviconPath: "./src/build/static/img/favicon.ico"
logFilePath: "./log/log.log"
server:
  port: 8080
