language: go
before_install:
  - go get github.com/stretchr/testify
  - go get github.com/garyburd/redigo/redis
  - go get github.com/ant0ine/go-json-rest/rest
  - go get github.com/patrickmn/go-cache
go:
  - 1.3
  - 1.4
  - 1.5
script: make test
services:
  - redis-server
